Mongol Tori 2.0: uart.h File Reference
uart.h File Reference
UART driver for STM32F4 series.
#include "stm32f405xx.h"
#include <stddef.h>
Data Structures
struct UART_Init_t
Configuration structure for UART peripheral.
struct UART_Handle_t
UART handle structure including DMA and buffers.
Macros
#define UART_MODE_TX (1U << 3)
#define UART_MODE_RX (1U << 2)
#define UART_MODE_TX_RX (UART_MODE_TX | UART_MODE_RX)
#define UART_BAUDRATE_1200 1200U
#define UART_BAUDRATE_2400 2400U
#define UART_BAUDRATE_4800 4800U
#define UART_BAUDRATE_9600 9600U
#define UART_BAUDRATE_19200 19200U
#define UART_BAUDRATE_38400 38400U
#define UART_BAUDRATE_57600 57600U
#define UART_BAUDRATE_115200 115200U
#define UART_BAUDRATE_230400 230400U
#define UART_BAUDRATE_460800 460800U
#define UART_BAUDRATE_921600 921600U
#define UART_BAUDRATE_1000000 1000000U
#define UART_PARITY_NONE (0U << 9)
#define UART_PARITY_EVEN (1U << 10)
#define UART_PARITY_ODD ((1U << 10) | (1U << 9))
#define UART_WORD_LEN_8BIT (0U << 12)
#define UART_WORD_LEN_9BIT (1U << 12)
#define UART_STOPBITS_1BIT (0U << 12)
#define UART_STOPBITS_0_5BIT (1U << 12)
#define UART_STOPBITS_2BIT (2U << 12)
#define UART_STOPBITS_1_5BIT (3U << 12)
#define UART_STATE_READY 0U
#define UART_STATE_BUSY_TX 1U
#define UART_STATE_BUSY_RX 2U
#define UART_HANDLE_STRUCT_DEFAULT(pUSART, baud)
Macro to initialize a default UART handle structure.
Enumerations
enum UART_Error_t { UART_ERROR = -1 , UART_OK = 0 }
Error codes for UART operations.
Functions
UART_Error_t UART_Init (UART_Handle_t *pHandle)
Initialize UART peripheral with given handle.
void UART_Transmit (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Transmit data via UART (blocking)
void UART_TransmitIT (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Transmit data via UART using interrupts.
void UART_TransmitDMA (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Transmit data via UART using DMA.
void UART_Receive (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Receive data via UART (blocking)
void UART_ReceiveIT (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Receive data via UART using interrupts.
void UART_ReceiveDMA (UART_Handle_t *pHandle, uint8_t *pData, uint32_t Size)
Receive data via UART using DMA.
Detailed Description
UART driver for STM32F4 series.
This file contains all the data structures, macros, and API function declarations required to initialize and use the UART peripheral with optional DMA support.
Macro Definition Documentation
UART_HANDLE_STRUCT_DEFAULT
#define UART_HANDLE_STRUCT_DEFAULT (pUSART, baud)
Value:
    (UART_Handle_t){                             \
        .Init = {                                \
            .pUSARTx = (pUSART),                 \
            .BaudRate = (baud),                  \
            .WordLen = UART_WORD_LEN_8BIT,       \
            .ParityConfig = UART_PARITY_NONE,    \
            .Direction = UART_MODE_TX_RX,        \
            .StopBits = UART_STOPBITS_1BIT},     \
        .pTxDMAStream = NULL,                    \
        .pRxDMAStream = NULL,                    \
        .TxDMAChannel = 0,                       \
        .RxDMAChannel = 0,                       \
        .BusyState = UART_STATE_READY,           \
        .pTxBuffer = NULL,                       \
        .pRxBuffer = NULL,                       \
        .TxSize = 0,                             \
        .RxSize = 0}
Macro to initialize a default UART handle structure.
Parameters
pUSART Pointer to USART peripheral
baud Baud rate
#define UART_HANDLE_STRUCT_DEFAULT(pUSART, baud) \
    (UART_Handle_t){                             \
        .Init = {                                \
            .pUSARTx = (pUSART),                 \
            .BaudRate = (baud),                  \
            .WordLen = UART_WORD_LEN_8BIT,       \
            .ParityConfig = UART_PARITY_NONE,    \
            .Direction = UART_MODE_TX_RX,        \
            .StopBits = UART_STOPBITS_1BIT},     \
        .pTxDMAStream = NULL,                    \
        .pRxDMAStream = NULL,                    \
        .TxDMAChannel = 0,                       \
        .RxDMAChannel = 0,                       \
        .BusyState = UART_STATE_READY,           \
        .pTxBuffer = NULL,                       \
        .pRxBuffer = NULL,                       \
        .TxSize = 0,                             \
        .RxSize = 0}
Enumeration Type Documentation
UART_Error_t
enum UART_Error_t
Error codes for UART operations.
Enumerator
UART_ERROR
General error
UART_OK
Operation successful
{
    UART_ERROR = -1,
    UART_OK = 0
} UART_Error_t;
Function Documentation
UART_Init()
UART_Error_t UART_Init (UART_Handle_t * pHandle)
Initialize UART peripheral with given handle.
Parameters
pHandle Pointer to UART handle structure
Returns
UART_OK on success, UART_ERROR on failure
{
    if (pHandle == NULL)
        return UART_ERROR;
    if (pHandle->Init.BaudRate < UART_BAUDRATE_1200 ||
        pHandle->Init.BaudRate > UART_BAUDRATE_1000000)
    {
        return UART_ERROR;
    }
    USART_TypeDef *USARTx = pHandle->Init.pUSARTx;
    // 1. Disable UART before config
    USARTx->CR1 &= ~USART_CR1_UE;
    // 2. Configure word length + parity + direction
    USARTx->CR1 &= ~(USART_CR1_M | USART_CR1_PCE | USART_CR1_PS |
                     USART_CR1_TE | USART_CR1_RE);
    USARTx->CR1 |= (pHandle->Init.WordLen |
                    pHandle->Init.ParityConfig |
                    pHandle->Init.Direction);
    // 3. Configure stop bits
    USARTx->CR2 &= ~(USART_CR2_STOP);
    USARTx->CR2 |= pHandle->Init.StopBits;
    // 4. Configure baud rate using default 16 MHz clock
    uint32_t periphClk = 16000000UL; // assuming HSI = 16 MHz
    uint32_t usartdiv;
    if ((USARTx->CR1 & USART_CR1_OVER8) == 0)
    {
        // oversampling by 16
        usartdiv = (periphClk + (pHandle->Init.BaudRate / 2U)) /
                   pHandle->Init.BaudRate;
        USARTx->BRR = usartdiv;
    }
    else
    {
        // oversampling by 8
        usartdiv = (2U * periphClk + (pHandle->Init.BaudRate / 2U)) /
                   pHandle->Init.BaudRate;
        USARTx->BRR = (usartdiv & 0xFFF0U) | ((usartdiv & 0x000FU) >> 1U);
    }
    // 5. Enable UART
    USARTx->CR1 |= USART_CR1_UE;
    // 6. Initialize handle runtime state
    pHandle->BusyState = UART_STATE_READY;
    pHandle->pTxBuffer = NULL;
    pHandle->pRxBuffer = NULL;
    pHandle->TxSize = 0;
    pHandle->RxSize = 0;
    return UART_OK;
}
References UART_Init_t::BaudRate, UART_Handle_t::BusyState, UART_Init_t::Direction, UART_Handle_t::Init, UART_Init_t::ParityConfig, UART_Handle_t::pRxBuffer, UART_Handle_t::pTxBuffer, UART_Init_t::pUSARTx, UART_Handle_t::RxSize, UART_Init_t::StopBits, UART_Handle_t::TxSize, UART_BAUDRATE_1000000, UART_BAUDRATE_1200, UART_ERROR, UART_OK, UART_STATE_READY, and UART_Init_t::WordLen.
Referenced by main().
UART_Receive()
void UART_Receive (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Receive data via UART (blocking)
UART_ReceiveDMA()
void UART_ReceiveDMA (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Receive data via UART using DMA.
{
    if (pHandle->BusyState != UART_STATE_READY || Size == 0 || pHandle->pRxDMAStream == NULL)
        return;
    // Mark UART busy
    pHandle->BusyState = UART_STATE_BUSY_RX;
    pHandle->pRxBuffer = pData;
    pHandle->RxSize = Size;
    USART_TypeDef *USARTx = pHandle->Init.pUSARTx;
    DMA_Stream_TypeDef *DMAxStream = pHandle->pRxDMAStream;
    // Enable UART DMA RX mode
    USARTx->CR3 |= USART_CR3_DMAR;
    // Disable DMA before config
    DMAxStream->CR &= ~DMA_SxCR_EN;
    while (DMAxStream->CR & DMA_SxCR_EN)
        ;
    // Peripheral = USART data register, Memory = user buffer
    DMAxStream->PAR = (uint32_t)&USARTx->DR;
    DMAxStream->M0AR = (uint32_t)pData;
    DMAxStream->NDTR = Size;
    uint32_t tmp = DMAxStream->CR;
    tmp &= ~(DMA_SxCR_CHSEL | DMA_SxCR_DIR | DMA_SxCR_MINC |
             DMA_SxCR_MSIZE | DMA_SxCR_PSIZE | DMA_SxCR_PL);
    tmp |= (pHandle->RxDMAChannel << DMA_SxCR_CHSEL_Pos) | // channel
           (0x0U << DMA_SxCR_DIR_Pos) |                    // Peripheral-to-memory
           DMA_SxCR_MINC |                                 // increment buffer
           (0x0U << DMA_SxCR_MSIZE_Pos) |                  // 8-bit memory
           (0x0U << DMA_SxCR_PSIZE_Pos) |                  // 8-bit peripheral
           (0x1U << DMA_SxCR_PL_Pos);                      // medium priority
    DMAxStream->CR = tmp;
    DMAxStream->CR |= DMA_SxCR_TCIE; // enable transfer complete interrupt
    DMAxStream->CR |= DMA_SxCR_EN;   // enable stream
}
References UART_Handle_t::BusyState, UART_Handle_t::Init, UART_Handle_t::pRxBuffer, UART_Handle_t::pRxDMAStream, UART_Init_t::pUSARTx, UART_Handle_t::RxDMAChannel, UART_Handle_t::RxSize, UART_STATE_BUSY_RX, and UART_STATE_READY.
Referenced by DMA2_Stream2_IRQHandler(), and main().
UART_ReceiveIT()
void UART_ReceiveIT (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Receive data via UART using interrupts.
UART_Transmit()
void UART_Transmit (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Transmit data via UART (blocking)
Parameters
pHandle Pointer to UART handle
pData Pointer to data buffer
Size Number of bytes to transmit
UART_TransmitDMA()
void UART_TransmitDMA (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Transmit data via UART using DMA.
{
    if (pHandle->BusyState != UART_STATE_READY || Size == 0 || pHandle->pTxDMAStream == NULL)
        return;
    // 1. Mark UART as busy
    pHandle->BusyState = UART_STATE_BUSY_TX;
    pHandle->pTxBuffer = pData;
    pHandle->TxSize = Size;
    USART_TypeDef *USARTx = pHandle->Init.pUSARTx;
    DMA_Stream_TypeDef *DMAxStream = pHandle->pTxDMAStream;
    // 2. Enable UART DMA TX mode
    USARTx->CR3 |= USART_CR3_DMAT;
    // 3. Disable DMA stream before configuration
    DMAxStream->CR &= ~DMA_SxCR_EN;
    while (DMAxStream->CR & DMA_SxCR_EN)
        ; // wait until fully disabled
    // 4. Configure peripheral and memory addresses
    DMAxStream->PAR = (uint32_t)&USARTx->DR; // peripheral register
    DMAxStream->M0AR = (uint32_t)pData;      // memory address
    // 5. Set number of data items
    DMAxStream->NDTR = Size;
    // 6. Configure stream control register (CR)
    uint32_t tmp = DMAxStream->CR;
    tmp &= ~(DMA_SxCR_CHSEL | DMA_SxCR_DIR | DMA_SxCR_MINC |
             DMA_SxCR_MSIZE | DMA_SxCR_PSIZE | DMA_SxCR_PL);
    tmp |= (pHandle->TxDMAChannel << DMA_SxCR_CHSEL_Pos) | // DMA channel
           (0x1U << DMA_SxCR_DIR_Pos) |                    // Memory-to-peripheral
           DMA_SxCR_MINC |                                 // Increment memory pointer
           (0x0U << DMA_SxCR_MSIZE_Pos) |                  // Memory size 8-bit
           (0x0U << DMA_SxCR_PSIZE_Pos) |                  // Peripheral size 8-bit
           (0x1U << DMA_SxCR_PL_Pos);                      // Medium priority
    DMAxStream->CR = tmp;
    // 7. Enable transfer complete interrupt (optional)
    DMAxStream->CR |= DMA_SxCR_TCIE;
    // 8. Enable DMA stream
    DMAxStream->CR |= DMA_SxCR_EN;
}
References UART_Handle_t::BusyState, UART_Handle_t::Init, UART_Handle_t::pTxBuffer, UART_Handle_t::pTxDMAStream, UART_Init_t::pUSARTx, UART_Handle_t::TxDMAChannel, UART_Handle_t::TxSize, UART_STATE_BUSY_TX, and UART_STATE_READY.
Referenced by DMA2_Stream2_IRQHandler().
UART_TransmitIT()
void UART_TransmitIT (UART_Handle_t * pHandle, uint8_t * pData, uint32_t Size)
Transmit data via UART using interrupts.